### ISSUE TITLE
Checklist

### ISSUE THREAD

**Issue by petrsvihlik** [petrsvihlik/rockys-cottage-backlog#14]
S sebou
- [ ] Repelent
- [ ] Nářadí z brna
- [ ] Pilka na dřevo z HK
- [ ] Kasička - W

Potrainy
- [ ] Věci na guláš
- [ ] Krabice tatranek
- [ ] Nealko - limonády, vody
- [ ] Diska/tatranky
- [ ] Chleba, horčice, kečup, buřty, okurky, rajčata (příp. další zelenina)
- [ ] Rohlíky, salámy

Nástroje ke stravování
- [ ] [Bečka](https://www.terno.cz/terno-hradec-kralove/?supermarket=hradec-kralove)
- [ ] [Pípa](https://www.chlazeni-pivo.cz/pujcovna-chlazeni-hradec-kralove.htm)
- [ ] Anální roztahovač
- [ ] Pumpička

Materiál
- [ ] Modrá skalice? Rozstrikovac...
- [ ] Špalek na dřevo
- [ ] Palubky z brna?
- [ ] Barel?
- [ ] Sprej proti hmyzu Wendy bere
- [ ] Čistící prostředky - W
- [ ] Lekarnicka
- [ ] Toaletak

Výlety
- [ ] http://www.ceske-lhotice.cz/turistika/turistika.html
- [ ] https://mapy.cz/s/zm27

**Comment by kordys** [comment]
Rozstrikovac mam...

**Comment by petrsvihlik** [comment]
great! (ted doufam, ze nemyslis sulina :D)

**Comment by kordys** [comment]
V tom pripade mam dva!
